@extends('dashboard.app')
@section('title', 'تفاصيل تذكرة الدعم')
@section('content')
<div class="mx-auto max-w-5xl space-y-5 p-4 sm:p-6" dir="rtl">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('user.support-tickets.index') }}" class="ui-text-soft">العودة إلى الطلبات</a><div class="mt-2 flex items-center gap-2"><h1 class="ui-title text-2xl font-bold">{{ $ticket->subject }}</h1><button type="button" class="ui-help-btn" data-ui-help-title="متابعة تذكرة الدعم" data-ui-help-body="تظهر هنا المحادثة وسجل تغيرات التذكرة. لا يمكنك إضافة متابعة قبل أول رد من الدعم التقني، ويمكنك إغلاق التذكرة أو إعادة فتحها عند الحاجة." aria-label="شرح متابعة التذكرة"><i class="fa-solid fa-lightbulb" aria-hidden="true"></i></button></div><p class="ui-text-muted">{{ $ticket->reference }} — {{ $ticket->category_label }} — أولوية {{ $ticket->priority_label }}</p></div><span class="ui-badge ui-badge-info">{{ $ticket->status_label }}</span></div>
    <section class="ui-card p-5"><h2 class="ui-title font-bold">المحادثة</h2><div class="mt-4 space-y-3">@forelse($ticket->messages as $message)<article class="ui-card-muted p-4"><div class="flex justify-between gap-3"><strong class="ui-title">{{ $message->sender_label }}</strong><time class="ui-text-muted">{{ $message->created_at?->format('Y-m-d H:i') }}</time></div><p class="ui-text-soft mt-2 whitespace-pre-line">{{ $message->message }}</p></article>@empty<p class="ui-text-muted">لا توجد رسائل.</p>@endforelse</div></section>
    @if(!in_array($ticket->status, ['closed', 'cancelled'], true) && $ticket->responded_at)<form method="POST" action="{{ route('user.support-tickets.messages.store', $ticket) }}" class="ui-card p-5">@csrf<label class="ui-text-soft mb-2 block">إضافة رسالة متابعة</label><textarea name="message" class="ui-input w-full" rows="4" required maxlength="4000"></textarea><button class="ui-btn ui-btn-primary mt-3">إرسال الرسالة</button></form>@elseif(!in_array($ticket->status, ['closed', 'cancelled'], true))<div class="ui-alert ui-alert-info">يمكنك إضافة رسالة متابعة بعد أول رد من الدعم التقني.</div>@endif
    <section class="ui-card p-5"><h2 class="ui-title font-bold">سجل التذكرة</h2><div class="mt-3 space-y-2">@foreach($ticket->events as $event)<div class="flex justify-between gap-3 ui-border-bottom py-2"><span class="ui-text-soft">{{ $event->label }}</span><time class="ui-text-muted">{{ $event->created_at?->format('Y-m-d H:i') }}</time></div>@endforeach</div></section>
    <div>@if(in_array($ticket->status, ['closed', 'cancelled'], true))<form method="POST" action="{{ route('user.support-tickets.reopen', $ticket) }}">@csrf @method('PATCH')<button class="ui-btn ui-btn-warning">إعادة فتح التذكرة</button></form>@else<form method="POST" action="{{ route('user.support-tickets.close', $ticket) }}" data-ui-confirm="سيتم إغلاق التذكرة ويمكن إعادة فتحها لاحقًا." data-ui-confirm-title="إغلاق التذكرة؟">@csrf @method('PATCH')<button class="ui-btn ui-btn-secondary">إغلاق التذكرة</button></form>@endif</div>
</div>
@endsection
