@extends('dashboard.app')
@section('title', 'إجراءات الدعم')
@section('content')
<div class="mx-auto max-w-7xl space-y-6 p-4 sm:p-6" dir="rtl">
    <div><div class="flex items-center gap-2"><h1 class="ui-title text-2xl font-bold">إجراءات</h1><button type="button" class="ui-help-btn" data-ui-help-title="إدارة العمليات المنتهية" data-ui-help-body="تجمع هذه الصفحة التذاكر والجلسات المنتهية وسجلات المحذوفات المكتملة. راجع كل سجل قبل حذفه؛ لا توجد مهمة انتظار أو عملية حذف تلقائية." aria-label="شرح صفحة الإجراءات"><i class="fa-solid fa-lightbulb" aria-hidden="true"></i></button></div><p class="ui-text-soft mt-1">عند فتح الصفحة تُعرض العمليات المنتهية والسجلات الجاهزة للمراجعة. جميع عمليات الحذف يدوية ولا تُستخدم مهام انتظار أو معالجة مجدولة.</p>@if($cancelledNow)<div class="ui-alert ui-alert-warning mt-3">أُلغي {{ $cancelledNow }} طلب غير مجاب عليه بعد انتهاء مهلة 7 أيام.</div>@endif</div>

    <section class="ui-card p-5"><h2 class="ui-title text-lg font-bold">التذاكر المنتهية والملغاة</h2><div class="ui-table-wrap mt-4"><table class="ui-table min-w-[820px]"><thead><tr><th>التذكرة</th><th>المالك</th><th>الحالة</th><th>آخر نشاط</th><th>الإجراء</th></tr></thead><tbody>@forelse($finishedTickets as $ticket)<tr><td><a class="ui-text-soft" href="{{ route('admin.support-tickets.show', $ticket) }}">{{ $ticket->reference }} — {{ $ticket->subject }}</a></td><td>{{ $ticket->owner?->name ?: 'غير متاح' }}</td><td>{{ $ticket->status_label }}</td><td>{{ $ticket->last_activity_at?->format('Y-m-d H:i') }}</td><td><form method="POST" action="{{ route('admin.support-tickets.destroy', $ticket) }}" data-ui-confirm="ستُنقل التذكرة إلى المحذوفات، ويمكن حذفها نهائيًا بعد انتهاء مدة الاحتفاظ." data-ui-confirm-title="حذف التذكرة المنتهية؟">@csrf @method('DELETE')<button class="ui-btn ui-btn-danger">حذف</button></form></td></tr>@empty<tr><td colspan="5" class="text-center ui-text-muted">لا توجد تذاكر منتهية.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $finishedTickets->links() }}</div></section>

    <section class="ui-card p-5"><h2 class="ui-title text-lg font-bold">جلسات الدخول المنتهية</h2><div class="ui-table-wrap mt-4"><table class="ui-table min-w-[820px]"><thead><tr><th>التذكرة</th><th>الحساب المستهدف</th><th>البداية</th><th>النهاية</th><th>الإجراء</th></tr></thead><tbody>@forelse($endedSessions as $session)<tr><td>{{ $session->ticket_reference }}</td><td>{{ $session->target_name }} — {{ $session->target_role === 'accountant' ? 'محاسب' : 'مالك متجر' }}</td><td>{{ $session->started_at?->format('Y-m-d H:i') }}</td><td>{{ $session->ended_at?->format('Y-m-d H:i') }}</td><td><form method="POST" action="{{ route('admin.support-actions.sessions.destroy', $session) }}" data-ui-confirm="سيتم حذف سجل جلسة الدخول المنتهية فقط." data-ui-confirm-title="حذف سجل الجلسة؟">@csrf @method('DELETE')<button class="ui-btn ui-btn-danger">حذف</button></form></td></tr>@empty<tr><td colspan="5" class="text-center ui-text-muted">لا توجد جلسات منتهية.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $endedSessions->links() }}</div></section>

    <section class="ui-card p-5"><h2 class="ui-title text-lg font-bold">محذوفات انتهت مهلة استعادتها</h2><div class="ui-table-wrap mt-4"><table class="ui-table min-w-[820px]"><thead><tr><th>المرجع</th><th>العنصر</th><th>المالك</th><th>انتهاء المهلة</th><th>الإجراء</th></tr></thead><tbody>@forelse($expiredDeletedItems as $item)<tr><td>{{ $item->reference }}</td><td>{{ $item->original_name ?: $item->type_label }}</td><td>{{ $item->owner?->name ?: 'غير متاح' }}</td><td>{{ $item->owner_restore_deadline?->format('Y-m-d H:i') }}</td><td><a href="{{ route('admin.support.archive.index', ['search' => $item->reference]) }}" class="ui-btn ui-btn-primary">مراجعة</a></td></tr>@empty<tr><td colspan="5" class="text-center ui-text-muted">لا توجد عناصر منتهية المهلة.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $expiredDeletedItems->links() }}</div></section>

    <section class="ui-card p-5"><h2 class="ui-title text-lg font-bold">سجلات عمليات المحذوفات المكتملة</h2><p class="ui-text-soft mt-1">تشمل العناصر التي استعيدت أو حُذفت نهائيًا. حذف السجل لا ينفذ أي تغيير إضافي على العنصر.</p><div class="ui-table-wrap mt-4"><table class="ui-table min-w-[820px]"><thead><tr><th>المرجع</th><th>العنصر</th><th>المالك</th><th>النتيجة</th><th>الإجراء</th></tr></thead><tbody>@forelse($completedDeletedItems as $item)<tr><td>{{ $item->reference }}</td><td>{{ $item->original_name ?: $item->type_label }}</td><td>{{ $item->owner?->name ?: 'غير متاح' }}</td><td>{{ $item->status === 'restored' ? 'تمت الاستعادة' : 'تم الحذف النهائي' }}</td><td><form method="POST" action="{{ route('admin.support-actions.completed-items.destroy', $item) }}" data-ui-confirm="سيتم حذف سجل العملية المكتملة فقط." data-ui-confirm-title="حذف سجل العملية؟">@csrf @method('DELETE')<button class="ui-btn ui-btn-danger">حذف</button></form></td></tr>@empty<tr><td colspan="5" class="text-center ui-text-muted">لا توجد سجلات مكتملة.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $completedDeletedItems->links() }}</div></section>

    <section class="ui-card p-5"><h2 class="ui-title text-lg font-bold">التذاكر المحذوفة</h2><p class="ui-text-soft mt-1">الحذف النهائي يدوي فقط، وبعد مرور 90 يومًا على الحذف.</p><div class="ui-table-wrap mt-4"><table class="ui-table min-w-[820px]"><thead><tr><th>التذكرة</th><th>تاريخ الحذف</th><th>موعد السماح</th><th>الإجراء</th></tr></thead><tbody>@forelse($deletedTickets as $ticket)<tr><td>{{ $ticket->reference }} — {{ $ticket->subject }}</td><td>{{ $ticket->deleted_at?->format('Y-m-d H:i') }}</td><td>{{ $ticket->deleted_at?->copy()->addDays(90)->format('Y-m-d H:i') }}</td><td>@if($ticket->deleted_at?->lte(now()->subDays(90)))<form method="POST" action="{{ route('admin.support-actions.tickets.purge', $ticket->id) }}" data-ui-confirm="سيتم حذف التذكرة ورسائلها وسجلها نهائيًا." data-ui-confirm-title="حذف نهائي؟">@csrf @method('DELETE')<button class="ui-btn ui-btn-danger">حذف نهائي</button></form>@else<span class="ui-text-muted">فترة الاحتفاظ سارية</span>@endif</td></tr>@empty<tr><td colspan="4" class="text-center ui-text-muted">لا توجد تذاكر محذوفة.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $deletedTickets->links() }}</div></section>
</div>
@endsection
