@extends('dashboard.app')
@section('title', 'متابعة تذكرة الدعم')
@section('content')
<div class="mx-auto max-w-6xl space-y-5 p-4 sm:p-6" dir="rtl">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('admin.support-tickets.index') }}" class="ui-text-soft">العودة إلى الطلبات</a><div class="mt-2 flex items-center gap-2"><h1 class="ui-title text-2xl font-bold">{{ $ticket->subject }}</h1><button type="button" class="ui-help-btn" data-ui-help-title="معالجة تذكرة الدعم" data-ui-help-body="اقرأ المحادثة وسجل التغييرات، أرسل ردًا واضحًا، ثم ابدأ الدخول إلى الحساب فقط إذا كانت المعالجة تتطلب ذلك. كل عملية أثناء الدخول ترتبط برقم هذه التذكرة." aria-label="شرح معالجة التذكرة"><i class="fa-solid fa-lightbulb" aria-hidden="true"></i></button></div><p class="ui-text-muted">{{ $ticket->reference }} — {{ $ticket->owner?->name }} — {{ $ticket->category_label }} — {{ $ticket->priority_label }}</p></div><span class="ui-badge ui-badge-info">{{ $ticket->status_label }}</span></div>
    <div class="grid grid-cols-1 gap-5 lg:grid-cols-3"><section class="ui-card p-5 lg:col-span-2"><h2 class="ui-title font-bold">المحادثة</h2><div class="mt-4 space-y-3">@foreach($ticket->messages as $message)<article class="ui-card-muted p-4"><div class="flex justify-between gap-3"><strong class="ui-title">{{ $message->sender_label }}</strong><time class="ui-text-muted">{{ $message->created_at?->format('Y-m-d H:i') }}</time></div><p class="ui-text-soft mt-2 whitespace-pre-line">{{ $message->message }}</p></article>@endforeach</div></section><aside class="ui-card p-5"><h2 class="ui-title font-bold">سجل التذكرة</h2><div class="mt-3 space-y-2">@foreach($ticket->events as $event)<div class="ui-border-bottom py-2"><div class="ui-text-soft">{{ $event->label }}</div><time class="ui-text-muted">{{ $event->created_at?->format('Y-m-d H:i') }}</time></div>@endforeach</div></aside></div>
    @if(!in_array($ticket->status, ['closed', 'cancelled'], true))<form method="POST" action="{{ route('admin.support-tickets.respond', $ticket) }}" class="ui-card p-5">@csrf @method('PATCH')<label class="ui-text-soft mb-2 block">رد الدعم التقني</label><textarea name="support_response" class="ui-input w-full" rows="4" required maxlength="4000"></textarea><div class="mt-3 flex flex-wrap gap-2"><button class="ui-btn ui-btn-primary">إرسال الرد</button><button form="start-session-form" class="ui-btn ui-btn-warning">دخول إلى الحساب</button></div></form><form id="start-session-form" method="POST" action="{{ route('admin.support-tickets.start', $ticket) }}">@csrf</form>@endif
    <div>@if(in_array($ticket->status, ['closed', 'cancelled'], true))<form method="POST" action="{{ route('admin.support-tickets.reopen', $ticket) }}">@csrf @method('PATCH')<button class="ui-btn ui-btn-warning">إعادة فتح التذكرة</button></form>@else<form method="POST" action="{{ route('admin.support-tickets.close', $ticket) }}">@csrf @method('PATCH')<button class="ui-btn ui-btn-secondary">إغلاق التذكرة</button></form>@endif</div>
</div>
@endsection
